name: Deploy App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: StateManager220411VMO
  WORKING_DIRECTORY: ./StateManager
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.WORKING_DIRECTORY }}
    - name: .net publish
      run: dotnet publish -c Release -o myapp
      working-directory: ${{ env.WORKING_DIRECTORY }}
    - name: Deploy To Azure App Service
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './StateManager/myapp'
