name: Deploy App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./StateManager
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./StateManager
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./StateManager
    - name: .net publish
      run: dotnet publish -c Release -o myapp
      working-directory: ./StateManager
    - name: Deploy To Azure App Service
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'StateManager220411VMO'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './StateManager/myapp'
